"""empty message

Revision ID: 03548f7c9c56
Revises: c4d189c57371
Create Date: 2021-08-20 00:23:20.035351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03548f7c9c56'
down_revision = 'c4d189c57371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cpu', sa.Text(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('osversion', sa.Text(), nullable=True),
    sa.Column('videocard', sa.Text(), nullable=True),
    sa.Column('diskspace', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gameinfo'))
    )
    op.create_table('illustinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cpu', sa.Text(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('osversion', sa.Text(), nullable=True),
    sa.Column('videocard', sa.Text(), nullable=True),
    sa.Column('diskspace', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_illustinfo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illustinfo')
    op.drop_table('gameinfo')
    # ### end Alembic commands ###
