"""empty message

Revision ID: 168d22f3509c
Revises: f996c6e23a7f
Create Date: 2021-11-05 18:11:05.127424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '168d22f3509c'
down_revision = 'f996c6e23a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graphic1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graphic2', sa.Text(), nullable=True))
        batch_op.drop_column('graphic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graphic', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('graphic2')
        batch_op.drop_column('graphic1')

    # ### end Alembic commands ###
