"""empty message

Revision ID: 2a3a0bb1b886
Revises: 888688d4afa3
Create Date: 2021-11-02 00:56:37.847505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a3a0bb1b886'
down_revision = '888688d4afa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('cpulist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cpuname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('codenum_UNIQUE')
        batch_op.drop_index('uq_user_email')
        batch_op.create_unique_constraint(batch_op.f('uq_user_codenum'), ['codenum'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_nickname'), ['nickname'])

    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_nickname'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_codenum'), type_='unique')
        batch_op.create_index('uq_user_email', ['nickname'], unique=False)
        batch_op.create_index('codenum_UNIQUE', ['codenum'], unique=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cpulist', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('cpuname',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_answer_id_answer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
