"""empty message

Revision ID: 33be6e0d67f6
Revises: bacb04a8fdda
Create Date: 2021-11-02 02:00:29.544051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33be6e0d67f6'
down_revision = 'bacb04a8fdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_codenum', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')
        batch_op.drop_column('codenum')

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('codenum_UNIQUE')
        batch_op.drop_index('uq_user_email')
        batch_op.create_unique_constraint(batch_op.f('uq_user_codenum'), ['codenum'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_nickname'), ['nickname'])

    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_nickname'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_codenum'), type_='unique')
        batch_op.create_index('uq_user_email', ['nickname'], unique=False)
        batch_op.create_index('codenum_UNIQUE', ['codenum'], unique=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codenum', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_question_user_codenum_user_pcinfo'), type_='foreignkey')
        batch_op.drop_column('user_codenum')

    # ### end Alembic commands ###
