"""empty message

Revision ID: 53c0459b0987
Revises: f4fd47ee5b48
Create Date: 2021-11-04 05:32:27.928492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c0459b0987'
down_revision = 'f4fd47ee5b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_index('fk_answer_voter_answer_id_answer_idx')
        batch_op.drop_index('fk_answer_voter_user_id_user_idx')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('codenum_UNIQUE')
        batch_op.drop_index('nickname_UNIQUE')
        batch_op.drop_index('username_UNIQUE')
        batch_op.create_unique_constraint(batch_op.f('uq_user_codenum'), ['codenum'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_nickname'), ['nickname'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_pcinfo_codenum_user'), 'user', ['codenum'], ['codenum'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_pcinfo_codenum_user'), type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_nickname'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_codenum'), type_='unique')
        batch_op.create_index('username_UNIQUE', ['username'], unique=False)
        batch_op.create_index('nickname_UNIQUE', ['nickname'], unique=False)
        batch_op.create_index('codenum_UNIQUE', ['codenum'], unique=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_codenum_user_pcinfo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_user'), type_='foreignkey')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_answer_id_answer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_user_codenum_user_pcinfo'), type_='foreignkey')

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.create_index('fk_answer_voter_user_id_user_idx', ['user_id'], unique=False)
        batch_op.create_index('fk_answer_voter_answer_id_answer_idx', ['answer_id'], unique=False)

    # ### end Alembic commands ###
