"""empty message

Revision ID: 866a640489dc
Revises: 16a4a2b43664
Create Date: 2021-11-02 16:45:24.491822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866a640489dc'
down_revision = '16a4a2b43664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
