"""empty message

Revision ID: bff1a2f3f069
Revises: c6848061e82e
Create Date: 2021-11-03 14:03:03.919509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bff1a2f3f069'
down_revision = 'c6848061e82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_answer_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_codenum')

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('answer_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_codenum')

    with op.batch_alter_table('cpulist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('cpuname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('codenum',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_codenum'), ['codenum'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_nickname'), ['nickname'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.alter_column('codenum',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_pcinfo_codenum_user'), 'user', ['codenum'], ['codenum'], ondelete='CASCADE')

    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videocard', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vcname',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user_pcinfo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_pcinfo_codenum_user'), type_='foreignkey')
        batch_op.alter_column('codenum',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_nickname'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_codenum'), type_='unique')
        batch_op.alter_column('codenum',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_codenum_user_pcinfo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_user'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cpulist', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('cpuname',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_codenum', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comment_answer_id_answer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.alter_column('create_date',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_answer_id_answer'), type_='foreignkey')
        batch_op.alter_column('answer_id',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_codenum', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_answer_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_user_id_user'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
