"""empty message

Revision ID: c4d189c57371
Revises: 56f42068e651
Create Date: 2021-08-19 23:59:04.101712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d189c57371'
down_revision = '56f42068e651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cpu', sa.Text(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('osversion', sa.Text(), nullable=True),
    sa.Column('videocard', sa.Text(), nullable=True),
    sa.Column('diskspace', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cadinfo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cadinfo')
    # ### end Alembic commands ###
