"""empty message

Revision ID: f17540afb61d
Revises: 2b14b2080fde
Create Date: 2021-10-11 15:29:22.666363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17540afb61d'
down_revision = '2b14b2080fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_to_db_test')
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_answer_voter_answer_id_answer'), 'answer', ['answer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('codenum_UNIQUE')
        batch_op.create_unique_constraint(batch_op.f('uq_user_codenum'), ['codenum'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_codenum'), type_='unique')
        batch_op.create_index('codenum_UNIQUE', ['codenum'], unique=False)

    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('illustinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gameinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cadinfo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_answer_id_answer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_voter_user_id_user'), type_='foreignkey')

    op.create_table('info_to_db_test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cpu', mysql.TEXT(), nullable=True),
    sa.Column('ram', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('osversion', mysql.TEXT(), nullable=True),
    sa.Column('videocard', mysql.TEXT(), nullable=True),
    sa.Column('diskspace', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
