"""empty message

Revision ID: f996c6e23a7f
Revises: 866a640489dc
Create Date: 2021-11-02 18:56:37.357230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f996c6e23a7f'
down_revision = '866a640489dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_codenum', sa.String(length=45), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_codenum', sa.String(length=45), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_codenum_user_pcinfo'), 'user_pcinfo', ['user_codenum'], ['codenum'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_user_codenum_user_pcinfo'), type_='foreignkey')
        batch_op.drop_column('user_codenum')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_user_codenum_user_pcinfo'), type_='foreignkey')
        batch_op.drop_column('user_codenum')

    # ### end Alembic commands ###
